services:
  frontend:
    container_name: Brandify-project
    build: 
      context: ./brandify-project
      dockerfile: Dockerfile
    ports:
      -"5173:5173"
    volumes:
      - ./Brandify-project:/app
    environment:
      - /app/node_modules
