services:
  frontend:
    container_name: Brandify-project
    build: 
      context: ./brandify
      dockerfile: ./src/dockerfile
    ports:
      -"5173:5173"
    volumes:
      -./app/Brandify-project
    environment:
      - NODE_ENV=development
